
title: Alexandre Bintz
description:
  en: "Alexandre Bintz - Engineer and maker"
  fr: "Alexandre Bintz - Ingénieur et maker"
author: Alexandre Bintz

email: alexandre@bintz.xyz
github_username: alexbinary
twitter_username: AlexFrom1991

theme: minima
plugins:
  - jekyll-feed