
title: Alexandre Bintz
description:
  en: "Alexandre Bintz"
  fr: "Alexandre Bintz"
author: Alexandre Bintz

email: alexandre@bintz.xyz
github_username: alexbinary
twitter_username: AlexFrom1991

theme: minima
plugins:
  - jekyll-feed

destination: ../build

langs:
  en:
    flag: 🇺🇸
    title_active: You are viewing the English version of this page
    title_inactive: Switch to English
  fr:
    flag: 🇫🇷
    title_active: Vous lisez la version en français de cette page
    title_inactive: Passer en français
