
title: Making something great
description: "
  Alexandre Bintz - maker, coder, thinker
  #programming #3dprinting #electronics #woodworking #LEGO #photography
  "

email: alexandre@bintz.xyz
github_username:  alexbinary

theme: minima
plugins:
  - jekyll-feed