
title: Let's make something great
description:
  Hi I'm Alex, I write about programming, woodworking, LEGO, electronics, and photography, mostly.

email: alexandre@bintz.xyz
github_username:  alexbinary

theme: minima
plugins:
  - jekyll-feed