
title: Alexandre Bintz
description:
  en: "Alexandre Bintz - Engineer and maker"
  fr: "Alexandre Bintz - Ingénieur et maker"
author: Alexandre Bintz

email: alexandre@bintz.xyz
github_username: alexbinary
twitter_username: AlexFrom1991

theme: minima
plugins:
  - jekyll-feed

langs:
  en:
    flag: 🇺🇸
    title_active: You are viewing the English version of this page
    title_inactive: Switch to English
    url: /en
    available_info: "This page is available <a href='%URL%'>in English %FLAG%</a>"
  fr:
    flag: 🇫🇷
    title_active: Vous lisez la version en français de cette page
    title_inactive: Passer en français
    url: /fr
    available_info: "Cette page est disponible <a href='%URL%'>en français %FLAG%</a>"
